/*
 * Java Card Mask for the C-JCRE
 *
 * Generated by
 * Java Card 2.1.2 Mask Builder (version 0.55)
 * Copyright (c) 2001 Sun Microsystems, Inc. All rights reserved.
 */
 
#ifdef __MASK_HEADER__


#define EXPORT_COMPONENT_BASE 0x0467
#define INITIAL_EXCEPTION_TABLE_LIST 0x05ce
#define ROMSIZE 1490
#define NON_ZERO_STATIC_FIELD_SIZE 0
#define ZERO_STATIC_FIELD_SIZE 0
#define NAPPLETS 0
#define NPACKAGES 5

#else

#include "profile.h"
#include "opcode.h"
#include "mask.h"

ROM_ARRAY(u8, rommask) = {

/* class@0x0000: public java/lang/Object */
0x00, 0xff, 0xff, 0x00, 0xff, 0x00, 0x00, 0x01, 0x00, 0x00, 
HIGH(0x000f), LOW(0x000f),		/* java/lang/Object/equals(Ljava/lang/Object;)Z */

/* method@0x000c: public java/lang/Object/<init>()V */
0x00, 0x10, 
/* 0x000e: */ _RETURN, 

/* method@0x000f: public java/lang/Object/equals(Ljava/lang/Object;)Z */
0x01, 0x20, 
/* 0x0011: */ _SCONST_0, 
/* 0x0012: */ _SRETURN, 

/* class@0x0013: public java/lang/Throwable */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x001d: public java/lang/Throwable/<init>()V */
0x01, 0x10, 
/* 0x001f: */ _ALOAD_0, 
/* 0x0020: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0023: */ _RETURN, 

/* class@0x0024: public java/lang/Exception */
0x00, HIGH(0x0013), LOW(0x0013), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x002e: public java/lang/Exception/<init>()V */
0x01, 0x10, 
/* 0x0030: */ _ALOAD_0, 
/* 0x0031: */ _INVOKESPECIAL, HIGH(0x001d), LOW(0x001d), 
/* 0x0034: */ _RETURN, 

/* class@0x0035: public java/lang/RuntimeException */
0x00, HIGH(0x0024), LOW(0x0024), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x003f: public java/lang/RuntimeException/<init>()V */
0x01, 0x10, 
/* 0x0041: */ _ALOAD_0, 
/* 0x0042: */ _INVOKESPECIAL, HIGH(0x002e), LOW(0x002e), 
/* 0x0045: */ _RETURN, 

/* class@0x0046: public java/lang/IndexOutOfBoundsException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0050: public java/lang/IndexOutOfBoundsException/<init>()V */
0x01, 0x10, 
/* 0x0052: */ _ALOAD_0, 
/* 0x0053: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x0056: */ _RETURN, 

/* class@0x0057: public java/lang/ArrayIndexOutOfBoundsException */
0x00, HIGH(0x0046), LOW(0x0046), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0061: public java/lang/ArrayIndexOutOfBoundsException/<init>()V */
0x01, 0x10, 
/* 0x0063: */ _ALOAD_0, 
/* 0x0064: */ _INVOKESPECIAL, HIGH(0x0050), LOW(0x0050), 
/* 0x0067: */ _RETURN, 

/* class@0x0068: public java/lang/NegativeArraySizeException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0072: public java/lang/NegativeArraySizeException/<init>()V */
0x01, 0x10, 
/* 0x0074: */ _ALOAD_0, 
/* 0x0075: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x0078: */ _RETURN, 

/* class@0x0079: public java/lang/NullPointerException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0083: public java/lang/NullPointerException/<init>()V */
0x01, 0x10, 
/* 0x0085: */ _ALOAD_0, 
/* 0x0086: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x0089: */ _RETURN, 

/* class@0x008a: public java/lang/ClassCastException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0094: public java/lang/ClassCastException/<init>()V */
0x01, 0x10, 
/* 0x0096: */ _ALOAD_0, 
/* 0x0097: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x009a: */ _RETURN, 

/* class@0x009b: public java/lang/ArithmeticException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x00a5: public java/lang/ArithmeticException/<init>()V */
0x01, 0x10, 
/* 0x00a7: */ _ALOAD_0, 
/* 0x00a8: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x00ab: */ _RETURN, 

/* class@0x00ac: public java/lang/SecurityException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x00b6: public java/lang/SecurityException/<init>()V */
0x01, 0x10, 
/* 0x00b8: */ _ALOAD_0, 
/* 0x00b9: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x00bc: */ _RETURN, 

/* class@0x00bd: public java/lang/ArrayStoreException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x00c7: public java/lang/ArrayStoreException/<init>()V */
0x01, 0x10, 
/* 0x00c9: */ _ALOAD_0, 
/* 0x00ca: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x00cd: */ _RETURN, 

/* class@0x00ce: public abstract interface javacard/framework/ISO7816 */
0x80, 
/* class@0x00cf: public abstract interface javacard/framework/PIN */
0x80, 
/* class@0x00d0: public abstract interface javacard/framework/Shareable */
0xc0, 
/* class@0x00d1: public abstract javacard/framework/Applet */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x07, 0x00, 0x00, 
HIGH(0x00e9), LOW(0x00e9),		/* javacard/framework/Applet/register()V */
HIGH(0x00ec), LOW(0x00ec),		/* javacard/framework/Applet/register([BSB)V */
HIGH(0x00ef), LOW(0x00ef),		/* javacard/framework/Applet/selectingApplet()Z */
HIGH(0x0101), LOW(0x0101),		/* javacard/framework/Applet/deselect()V */
HIGH(0x0104), LOW(0x0104),		/* javacard/framework/Applet/getShareableInterfaceObject(Ljavacard/framework/AID;B)Ljavacard/framework/Shareable; */
HIGH(0x00fd), LOW(0x00fd),		/* javacard/framework/Applet/select()Z */
HIGH(0x0108), LOW(0x0108),		/* javacard/framework/Applet/process(Ljavacard/framework/APDU;)V */

/* method@0x00e9: protected final javacard/framework/Applet/register()V */
0x00, 0x10, 
/* 0x00eb: */ _RETURN, 

/* method@0x00ec: protected final javacard/framework/Applet/register([BSB)V */
0x00, 0x40, 
/* 0x00ee: */ _RETURN, 

/* method@0x00ef: protected final javacard/framework/Applet/selectingApplet()Z */
0x01, 0x10, 
/* 0x00f1: */ _SCONST_0, 
/* 0x00f2: */ _SRETURN, 

/* method@0x00f3: protected javacard/framework/Applet/<init>()V */
0x01, 0x10, 
/* 0x00f5: */ _ALOAD_0, 
/* 0x00f6: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x00f9: */ _RETURN, 

/* method@0x00fa: public static javacard/framework/Applet/install([BSB)V */
0x00, 0x30, 
/* 0x00fc: */ _RETURN, 

/* method@0x00fd: public javacard/framework/Applet/select()Z */
0x01, 0x10, 
/* 0x00ff: */ _SCONST_0, 
/* 0x0100: */ _SRETURN, 

/* method@0x0101: public javacard/framework/Applet/deselect()V */
0x00, 0x10, 
/* 0x0103: */ _RETURN, 

/* method@0x0104: public javacard/framework/Applet/getShareableInterfaceObject(Ljavacard/framework/AID;B)Ljavacard/framework/Shareable; */
0x01, 0x30, 
/* 0x0106: */ _ACONST_NULL, 
/* 0x0107: */ _ARETURN, 

/* method@0x0108: public abstract javacard/framework/Applet/process(Ljavacard/framework/APDU;)V */
0x40, 0x20, 

/* class@0x010a: public javacard/framework/CardException */
0x00, HIGH(0x0024), LOW(0x0024), 0x00, 0xff, 0x00, 0x01, 0x02, 0x00, 0x00, 
HIGH(0x011f), LOW(0x011f),		/* javacard/framework/CardException/getReason()S */
HIGH(0x0123), LOW(0x0123),		/* javacard/framework/CardException/setReason(S)V */

/* method@0x0118: public javacard/framework/CardException/<init>(S)V */
0x01, 0x20, 
/* 0x011a: */ _ALOAD_0, 
/* 0x011b: */ _INVOKESPECIAL, HIGH(0x002e), LOW(0x002e), 
/* 0x011e: */ _RETURN, 

/* method@0x011f: public javacard/framework/CardException/getReason()S */
0x01, 0x10, 
/* 0x0121: */ _SCONST_0, 
/* 0x0122: */ _SRETURN, 

/* method@0x0123: public javacard/framework/CardException/setReason(S)V */
0x00, 0x20, 
/* 0x0125: */ _RETURN, 

/* method@0x0126: public static javacard/framework/CardException/throwIt(S)V */
0x00, 0x10, 
/* 0x0128: */ _RETURN, 

/* class@0x0129: public javacard/framework/CardRuntimeException */
0x00, HIGH(0x0035), LOW(0x0035), 0x00, 0xff, 0x00, 0x01, 0x02, 0x00, 0x00, 
HIGH(0x013e), LOW(0x013e),		/* javacard/framework/CardRuntimeException/getReason()S */
HIGH(0x0142), LOW(0x0142),		/* javacard/framework/CardRuntimeException/setReason(S)V */

/* method@0x0137: public javacard/framework/CardRuntimeException/<init>(S)V */
0x01, 0x20, 
/* 0x0139: */ _ALOAD_0, 
/* 0x013a: */ _INVOKESPECIAL, HIGH(0x003f), LOW(0x003f), 
/* 0x013d: */ _RETURN, 

/* method@0x013e: public javacard/framework/CardRuntimeException/getReason()S */
0x01, 0x10, 
/* 0x0140: */ _SCONST_0, 
/* 0x0141: */ _SRETURN, 

/* method@0x0142: public javacard/framework/CardRuntimeException/setReason(S)V */
0x00, 0x20, 
/* 0x0144: */ _RETURN, 

/* method@0x0145: public static javacard/framework/CardRuntimeException/throwIt(S)V */
0x00, 0x10, 
/* 0x0147: */ _RETURN, 

/* class@0x0148: public final javacard/framework/AID */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x00, 0x05, 0x00, 0x00, 
HIGH(0x0167), LOW(0x0167),		/* javacard/framework/AID/equals(Ljava/lang/Object;)Z */
HIGH(0x0173), LOW(0x0173),		/* javacard/framework/AID/RIDEquals(Ljavacard/framework/AID;)Z */
HIGH(0x016b), LOW(0x016b),		/* javacard/framework/AID/equals([BSB)Z */
HIGH(0x0163), LOW(0x0163),		/* javacard/framework/AID/getBytes([BS)B */
HIGH(0x016f), LOW(0x016f),		/* javacard/framework/AID/partialEquals([BSB)Z */

/* method@0x015c: public javacard/framework/AID/<init>([BSB)V */
0x01, 0x40, 
/* 0x015e: */ _ALOAD_0, 
/* 0x015f: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0162: */ _RETURN, 

/* method@0x0163: public javacard/framework/AID/getBytes([BS)B */
0x01, 0x30, 
/* 0x0165: */ _SCONST_0, 
/* 0x0166: */ _SRETURN, 

/* method@0x0167: public javacard/framework/AID/equals(Ljava/lang/Object;)Z */
0x01, 0x20, 
/* 0x0169: */ _SCONST_0, 
/* 0x016a: */ _SRETURN, 

/* method@0x016b: public javacard/framework/AID/equals([BSB)Z */
0x01, 0x40, 
/* 0x016d: */ _SCONST_0, 
/* 0x016e: */ _SRETURN, 

/* method@0x016f: public javacard/framework/AID/partialEquals([BSB)Z */
0x01, 0x40, 
/* 0x0171: */ _SCONST_0, 
/* 0x0172: */ _SRETURN, 

/* method@0x0173: public javacard/framework/AID/RIDEquals(Ljavacard/framework/AID;)Z */
0x01, 0x20, 
/* 0x0175: */ _SCONST_0, 
/* 0x0176: */ _SRETURN, 

/* class@0x0177: public javacard/framework/ISOException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x0181: public javacard/framework/ISOException/<init>(S)V */
0x02, 0x20, 
/* 0x0183: */ _ALOAD_0, 
/* 0x0184: */ _SLOAD_1, 
/* 0x0185: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x0188: */ _RETURN, 

/* method@0x0189: public static javacard/framework/ISOException/throwIt(S)V */
0x00, 0x10, 
/* 0x018b: */ _RETURN, 

/* class@0x018c: public final javacard/framework/JCSystem */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x0196:  javacard/framework/JCSystem/<init>()V */
0x01, 0x10, 
/* 0x0198: */ _ALOAD_0, 
/* 0x0199: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x019c: */ _RETURN, 

/* method@0x019d: public static javacard/framework/JCSystem/isTransient(Ljava/lang/Object;)B */
0x01, 0x10, 
/* 0x019f: */ _SCONST_0, 
/* 0x01a0: */ _SRETURN, 

/* method@0x01a1: public static javacard/framework/JCSystem/makeTransientBooleanArray(SB)[Z */
0x01, 0x20, 
/* 0x01a3: */ _ACONST_NULL, 
/* 0x01a4: */ _ARETURN, 

/* method@0x01a5: public static javacard/framework/JCSystem/makeTransientByteArray(SB)[B */
0x01, 0x20, 
/* 0x01a7: */ _ACONST_NULL, 
/* 0x01a8: */ _ARETURN, 

/* method@0x01a9: public static javacard/framework/JCSystem/makeTransientShortArray(SB)[S */
0x01, 0x20, 
/* 0x01ab: */ _ACONST_NULL, 
/* 0x01ac: */ _ARETURN, 

/* method@0x01ad: public static javacard/framework/JCSystem/makeTransientObjectArray(SB)[Ljava/lang/Object; */
0x01, 0x20, 
/* 0x01af: */ _ACONST_NULL, 
/* 0x01b0: */ _ARETURN, 

/* method@0x01b1: public static javacard/framework/JCSystem/getVersion()S */
0x01, 0x00, 
/* 0x01b3: */ _SCONST_0, 
/* 0x01b4: */ _SRETURN, 

/* method@0x01b5: public static javacard/framework/JCSystem/getAID()Ljavacard/framework/AID; */
0x01, 0x00, 
/* 0x01b7: */ _ACONST_NULL, 
/* 0x01b8: */ _ARETURN, 

/* method@0x01b9: public static javacard/framework/JCSystem/lookupAID([BSB)Ljavacard/framework/AID; */
0x01, 0x30, 
/* 0x01bb: */ _ACONST_NULL, 
/* 0x01bc: */ _ARETURN, 

/* method@0x01bd: public static javacard/framework/JCSystem/beginTransaction()V */
0x00, 0x00, 
/* 0x01bf: */ _RETURN, 

/* method@0x01c0: public static javacard/framework/JCSystem/abortTransaction()V */
0x00, 0x00, 
/* 0x01c2: */ _RETURN, 

/* method@0x01c3: public static javacard/framework/JCSystem/commitTransaction()V */
0x00, 0x00, 
/* 0x01c5: */ _RETURN, 

/* method@0x01c6: public static javacard/framework/JCSystem/getTransactionDepth()B */
0x01, 0x00, 
/* 0x01c8: */ _SCONST_0, 
/* 0x01c9: */ _SRETURN, 

/* method@0x01ca: public static javacard/framework/JCSystem/getUnusedCommitCapacity()S */
0x01, 0x00, 
/* 0x01cc: */ _SCONST_0, 
/* 0x01cd: */ _SRETURN, 

/* method@0x01ce: public static javacard/framework/JCSystem/getMaxCommitCapacity()S */
0x01, 0x00, 
/* 0x01d0: */ _SCONST_0, 
/* 0x01d1: */ _SRETURN, 

/* method@0x01d2: public static javacard/framework/JCSystem/getPreviousContextAID()Ljavacard/framework/AID; */
0x01, 0x00, 
/* 0x01d4: */ _ACONST_NULL, 
/* 0x01d5: */ _ARETURN, 

/* method@0x01d6: public static javacard/framework/JCSystem/getAppletShareableInterfaceObject(Ljavacard/framework/AID;B)Ljavacard/framework/Shareable; */
0x01, 0x20, 
/* 0x01d8: */ _ACONST_NULL, 
/* 0x01d9: */ _ARETURN, 

/* class@0x01da: public javacard/framework/OwnerPIN */
0x01, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x08, 0x00, 0x00, 
HIGH(0x020d), LOW(0x020d),		/* javacard/framework/OwnerPIN/check([BSB)Z */
HIGH(0x0209), LOW(0x0209),		/* javacard/framework/OwnerPIN/getTriesRemaining()B */
HIGH(0x0202), LOW(0x0202),		/* javacard/framework/OwnerPIN/getValidatedFlag()Z */
HIGH(0x0211), LOW(0x0211),		/* javacard/framework/OwnerPIN/isValidated()Z */
HIGH(0x0215), LOW(0x0215),		/* javacard/framework/OwnerPIN/reset()V */
HIGH(0x021b), LOW(0x021b),		/* javacard/framework/OwnerPIN/resetAndUnblock()V */
HIGH(0x0206), LOW(0x0206),		/* javacard/framework/OwnerPIN/setValidatedFlag(Z)V */
HIGH(0x0218), LOW(0x0218),		/* javacard/framework/OwnerPIN/update([BSB)V */
HIGH(0x00cf), LOW(0x00cf), 4, 1, 2, 4, 5, 

/* method@0x01fb: public javacard/framework/OwnerPIN/<init>(BB)V */
0x01, 0x30, 
/* 0x01fd: */ _ALOAD_0, 
/* 0x01fe: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0201: */ _RETURN, 

/* method@0x0202: protected javacard/framework/OwnerPIN/getValidatedFlag()Z */
0x01, 0x10, 
/* 0x0204: */ _SCONST_0, 
/* 0x0205: */ _SRETURN, 

/* method@0x0206: protected javacard/framework/OwnerPIN/setValidatedFlag(Z)V */
0x00, 0x20, 
/* 0x0208: */ _RETURN, 

/* method@0x0209: public javacard/framework/OwnerPIN/getTriesRemaining()B */
0x01, 0x10, 
/* 0x020b: */ _SCONST_0, 
/* 0x020c: */ _SRETURN, 

/* method@0x020d: public javacard/framework/OwnerPIN/check([BSB)Z */
0x01, 0x40, 
/* 0x020f: */ _SCONST_0, 
/* 0x0210: */ _SRETURN, 

/* method@0x0211: public javacard/framework/OwnerPIN/isValidated()Z */
0x01, 0x10, 
/* 0x0213: */ _SCONST_0, 
/* 0x0214: */ _SRETURN, 

/* method@0x0215: public javacard/framework/OwnerPIN/reset()V */
0x00, 0x10, 
/* 0x0217: */ _RETURN, 

/* method@0x0218: public javacard/framework/OwnerPIN/update([BSB)V */
0x00, 0x40, 
/* 0x021a: */ _RETURN, 

/* method@0x021b: public javacard/framework/OwnerPIN/resetAndUnblock()V */
0x00, 0x10, 
/* 0x021d: */ _RETURN, 

/* class@0x021e: public final javacard/framework/APDU */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x0a, 0x00, 0x00, 
HIGH(0x0243), LOW(0x0243),		/* javacard/framework/APDU/getBuffer()[B */
HIGH(0x0253), LOW(0x0253),		/* javacard/framework/APDU/getNAD()B */
HIGH(0x0262), LOW(0x0262),		/* javacard/framework/APDU/receiveBytes(S)S */
HIGH(0x026a), LOW(0x026a),		/* javacard/framework/APDU/sendBytes(SS)V */
HIGH(0x026d), LOW(0x026d),		/* javacard/framework/APDU/sendBytesLong([BSS)V */
HIGH(0x0266), LOW(0x0266),		/* javacard/framework/APDU/setIncomingAndReceive()S */
HIGH(0x0257), LOW(0x0257),		/* javacard/framework/APDU/setOutgoing()S */
HIGH(0x0270), LOW(0x0270),		/* javacard/framework/APDU/setOutgoingAndSend(SS)V */
HIGH(0x025f), LOW(0x025f),		/* javacard/framework/APDU/setOutgoingLength(S)V */
HIGH(0x025b), LOW(0x025b),		/* javacard/framework/APDU/setOutgoingNoChaining()S */

/* method@0x023c:  javacard/framework/APDU/<init>()V */
0x01, 0x10, 
/* 0x023e: */ _ALOAD_0, 
/* 0x023f: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0242: */ _RETURN, 

/* method@0x0243: public javacard/framework/APDU/getBuffer()[B */
0x01, 0x10, 
/* 0x0245: */ _ACONST_NULL, 
/* 0x0246: */ _ARETURN, 

/* method@0x0247: public static javacard/framework/APDU/getInBlockSize()S */
0x01, 0x00, 
/* 0x0249: */ _SCONST_0, 
/* 0x024a: */ _SRETURN, 

/* method@0x024b: public static javacard/framework/APDU/getOutBlockSize()S */
0x01, 0x00, 
/* 0x024d: */ _SCONST_0, 
/* 0x024e: */ _SRETURN, 

/* method@0x024f: public static javacard/framework/APDU/getProtocol()B */
0x01, 0x00, 
/* 0x0251: */ _SCONST_0, 
/* 0x0252: */ _SRETURN, 

/* method@0x0253: public javacard/framework/APDU/getNAD()B */
0x01, 0x10, 
/* 0x0255: */ _SCONST_0, 
/* 0x0256: */ _SRETURN, 

/* method@0x0257: public javacard/framework/APDU/setOutgoing()S */
0x01, 0x10, 
/* 0x0259: */ _SCONST_0, 
/* 0x025a: */ _SRETURN, 

/* method@0x025b: public javacard/framework/APDU/setOutgoingNoChaining()S */
0x01, 0x10, 
/* 0x025d: */ _SCONST_0, 
/* 0x025e: */ _SRETURN, 

/* method@0x025f: public javacard/framework/APDU/setOutgoingLength(S)V */
0x00, 0x20, 
/* 0x0261: */ _RETURN, 

/* method@0x0262: public javacard/framework/APDU/receiveBytes(S)S */
0x01, 0x20, 
/* 0x0264: */ _SCONST_0, 
/* 0x0265: */ _SRETURN, 

/* method@0x0266: public javacard/framework/APDU/setIncomingAndReceive()S */
0x01, 0x10, 
/* 0x0268: */ _SCONST_0, 
/* 0x0269: */ _SRETURN, 

/* method@0x026a: public javacard/framework/APDU/sendBytes(SS)V */
0x00, 0x30, 
/* 0x026c: */ _RETURN, 

/* method@0x026d: public javacard/framework/APDU/sendBytesLong([BSS)V */
0x00, 0x40, 
/* 0x026f: */ _RETURN, 

/* method@0x0270: public javacard/framework/APDU/setOutgoingAndSend(SS)V */
0x00, 0x30, 
/* 0x0272: */ _RETURN, 

/* method@0x0273: public static javacard/framework/APDU/waitExtension()V */
0x00, 0x00, 
/* 0x0275: */ _RETURN, 

/* class@0x0276: public javacard/framework/PINException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x0280: public javacard/framework/PINException/<init>(S)V */
0x02, 0x20, 
/* 0x0282: */ _ALOAD_0, 
/* 0x0283: */ _SLOAD_1, 
/* 0x0284: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x0287: */ _RETURN, 

/* method@0x0288: public static javacard/framework/PINException/throwIt(S)V */
0x00, 0x10, 
/* 0x028a: */ _RETURN, 

/* class@0x028b: public javacard/framework/APDUException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x0295: public javacard/framework/APDUException/<init>(S)V */
0x02, 0x20, 
/* 0x0297: */ _ALOAD_0, 
/* 0x0298: */ _SLOAD_1, 
/* 0x0299: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x029c: */ _RETURN, 

/* method@0x029d: public static javacard/framework/APDUException/throwIt(S)V */
0x00, 0x10, 
/* 0x029f: */ _RETURN, 

/* class@0x02a0: public javacard/framework/SystemException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x02aa: public javacard/framework/SystemException/<init>(S)V */
0x02, 0x20, 
/* 0x02ac: */ _ALOAD_0, 
/* 0x02ad: */ _SLOAD_1, 
/* 0x02ae: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x02b1: */ _RETURN, 

/* method@0x02b2: public static javacard/framework/SystemException/throwIt(S)V */
0x00, 0x10, 
/* 0x02b4: */ _RETURN, 

/* class@0x02b5: public javacard/framework/TransactionException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x02bf: public javacard/framework/TransactionException/<init>(S)V */
0x02, 0x20, 
/* 0x02c1: */ _ALOAD_0, 
/* 0x02c2: */ _SLOAD_1, 
/* 0x02c3: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x02c6: */ _RETURN, 

/* method@0x02c7: public static javacard/framework/TransactionException/throwIt(S)V */
0x00, 0x10, 
/* 0x02c9: */ _RETURN, 

/* class@0x02ca: public javacard/framework/UserException */
0x00, HIGH(0x010a), LOW(0x010a), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x02d4: public javacard/framework/UserException/<init>()V */
0x02, 0x10, 
/* 0x02d6: */ _ALOAD_0, 
/* 0x02d7: */ _SCONST_0, 
/* 0x02d8: */ _INVOKESPECIAL, HIGH(0x0118), LOW(0x0118), 
/* 0x02db: */ _RETURN, 

/* method@0x02dc: public javacard/framework/UserException/<init>(S)V */
0x02, 0x20, 
/* 0x02de: */ _ALOAD_0, 
/* 0x02df: */ _SLOAD_1, 
/* 0x02e0: */ _INVOKESPECIAL, HIGH(0x0118), LOW(0x0118), 
/* 0x02e3: */ _RETURN, 

/* method@0x02e4: public static javacard/framework/UserException/throwIt(S)V */
0x00, 0x10, 
/* 0x02e6: */ _RETURN, 

/* class@0x02e7: public javacard/framework/Util */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x02f1: public static final javacard/framework/Util/arrayCopy([BS[BSS)S */
0x01, 0x50, 
/* 0x02f3: */ _SCONST_0, 
/* 0x02f4: */ _SRETURN, 

/* method@0x02f5: public static final javacard/framework/Util/arrayCopyNonAtomic([BS[BSS)S */
0x01, 0x50, 
/* 0x02f7: */ _SCONST_0, 
/* 0x02f8: */ _SRETURN, 

/* method@0x02f9: public static final javacard/framework/Util/arrayFillNonAtomic([BSSB)S */
0x01, 0x40, 
/* 0x02fb: */ _SCONST_0, 
/* 0x02fc: */ _SRETURN, 

/* method@0x02fd: public static final javacard/framework/Util/arrayCompare([BS[BSS)B */
0x01, 0x50, 
/* 0x02ff: */ _SCONST_0, 
/* 0x0300: */ _SRETURN, 

/* method@0x0301: public static final javacard/framework/Util/makeShort(BB)S */
0x01, 0x20, 
/* 0x0303: */ _SCONST_0, 
/* 0x0304: */ _SRETURN, 

/* method@0x0305: public static final javacard/framework/Util/getShort([BS)S */
0x01, 0x20, 
/* 0x0307: */ _SCONST_0, 
/* 0x0308: */ _SRETURN, 

/* method@0x0309: public static final javacard/framework/Util/setShort([BSS)S */
0x01, 0x30, 
/* 0x030b: */ _SCONST_0, 
/* 0x030c: */ _SRETURN, 

/* method@0x030d:  javacard/framework/Util/<init>()V */
0x01, 0x10, 
/* 0x030f: */ _ALOAD_0, 
/* 0x0310: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0313: */ _RETURN, 

/* class@0x0314: public abstract interface javacard/security/Key */
0x80, 
/* class@0x0315: public abstract interface javacard/security/DSAKey */
0x80, 
/* class@0x0316: public abstract interface javacard/security/PrivateKey */
0x81, HIGH(0x0314), LOW(0x0314), 

/* class@0x0319: public abstract interface javacard/security/PublicKey */
0x81, HIGH(0x0314), LOW(0x0314), 

/* class@0x031c: public abstract interface javacard/security/SecretKey */
0x81, HIGH(0x0314), LOW(0x0314), 

/* class@0x031f: public abstract interface javacard/security/DSAPrivateKey */
0x83, HIGH(0x0314), LOW(0x0314), 
HIGH(0x0316), LOW(0x0316), 
HIGH(0x0315), LOW(0x0315), 

/* class@0x0326: public abstract interface javacard/security/DSAPublicKey */
0x83, HIGH(0x0314), LOW(0x0314), 
HIGH(0x0319), LOW(0x0319), 
HIGH(0x0315), LOW(0x0315), 

/* class@0x032d: public abstract interface javacard/security/RSAPrivateCrtKey */
0x82, HIGH(0x0314), LOW(0x0314), 
HIGH(0x0316), LOW(0x0316), 

/* class@0x0332: public abstract interface javacard/security/RSAPrivateKey */
0x82, HIGH(0x0314), LOW(0x0314), 
HIGH(0x0316), LOW(0x0316), 

/* class@0x0337: public abstract interface javacard/security/RSAPublicKey */
0x82, HIGH(0x0314), LOW(0x0314), 
HIGH(0x0319), LOW(0x0319), 

/* class@0x033c: public abstract interface javacard/security/DESKey */
0x82, HIGH(0x0314), LOW(0x0314), 
HIGH(0x031c), LOW(0x031c), 

/* class@0x0341: public final javacard/security/KeyPair */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x03, 0x00, 0x00, 
HIGH(0x0351), LOW(0x0351),		/* javacard/security/KeyPair/genKeyPair()V */
HIGH(0x0366), LOW(0x0366),		/* javacard/security/KeyPair/getPrivate()Ljavacard/security/PrivateKey; */
HIGH(0x0362), LOW(0x0362),		/* javacard/security/KeyPair/getPublic()Ljavacard/security/PublicKey; */

/* method@0x0351: public final javacard/security/KeyPair/genKeyPair()V */
0x00, 0x10, 
/* 0x0353: */ _RETURN, 

/* method@0x0354: public javacard/security/KeyPair/<init>(BS)V */
0x01, 0x30, 
/* 0x0356: */ _ALOAD_0, 
/* 0x0357: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x035a: */ _RETURN, 

/* method@0x035b: public javacard/security/KeyPair/<init>(Ljavacard/security/PublicKey;Ljavacard/security/PrivateKey;)V */
0x01, 0x30, 
/* 0x035d: */ _ALOAD_0, 
/* 0x035e: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0361: */ _RETURN, 

/* method@0x0362: public javacard/security/KeyPair/getPublic()Ljavacard/security/PublicKey; */
0x01, 0x10, 
/* 0x0364: */ _ACONST_NULL, 
/* 0x0365: */ _ARETURN, 

/* method@0x0366: public javacard/security/KeyPair/getPrivate()Ljavacard/security/PrivateKey; */
0x01, 0x10, 
/* 0x0368: */ _ACONST_NULL, 
/* 0x0369: */ _ARETURN, 

/* class@0x036a: public abstract javacard/security/MessageDigest */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x05, 0x00, 0x00, 
HIGH(0x038f), LOW(0x038f),		/* javacard/security/MessageDigest/doFinal([BSS[BS)S */
HIGH(0x0389), LOW(0x0389),		/* javacard/security/MessageDigest/getAlgorithm()B */
HIGH(0x038b), LOW(0x038b),		/* javacard/security/MessageDigest/getLength()B */
HIGH(0x038d), LOW(0x038d),		/* javacard/security/MessageDigest/reset()V */
HIGH(0x0391), LOW(0x0391),		/* javacard/security/MessageDigest/update([BSS)V */

/* method@0x037e: public static final javacard/security/MessageDigest/getInstance(BZ)Ljavacard/security/MessageDigest; */
0x01, 0x20, 
/* 0x0380: */ _ACONST_NULL, 
/* 0x0381: */ _ARETURN, 

/* method@0x0382: protected javacard/security/MessageDigest/<init>()V */
0x01, 0x10, 
/* 0x0384: */ _ALOAD_0, 
/* 0x0385: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x0388: */ _RETURN, 

/* method@0x0389: public abstract javacard/security/MessageDigest/getAlgorithm()B */
0x40, 0x10, 

/* method@0x038b: public abstract javacard/security/MessageDigest/getLength()B */
0x40, 0x10, 

/* method@0x038d: public abstract javacard/security/MessageDigest/reset()V */
0x40, 0x10, 

/* method@0x038f: public abstract javacard/security/MessageDigest/doFinal([BSS[BS)S */
0x40, 0x60, 

/* method@0x0391: public abstract javacard/security/MessageDigest/update([BSS)V */
0x40, 0x40, 

/* class@0x0393: public javacard/security/CryptoException */
0x00, HIGH(0x0129), LOW(0x0129), 0x00, 0xff, 0x00, 0x03, 0x00, 0x00, 0x00, 

/* method@0x039d: public javacard/security/CryptoException/<init>(S)V */
0x02, 0x20, 
/* 0x039f: */ _ALOAD_0, 
/* 0x03a0: */ _SLOAD_1, 
/* 0x03a1: */ _INVOKESPECIAL, HIGH(0x0137), LOW(0x0137), 
/* 0x03a4: */ _RETURN, 

/* method@0x03a5: public static javacard/security/CryptoException/throwIt(S)V */
0x00, 0x10, 
/* 0x03a7: */ _RETURN, 

/* class@0x03a8: public abstract javacard/security/RandomData */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x02, 0x00, 0x00, 
HIGH(0x03c1), LOW(0x03c1),		/* javacard/security/RandomData/generateData([BSS)V */
HIGH(0x03c3), LOW(0x03c3),		/* javacard/security/RandomData/setSeed([BSS)V */

/* method@0x03b6: public static final javacard/security/RandomData/getInstance(B)Ljavacard/security/RandomData; */
0x01, 0x10, 
/* 0x03b8: */ _ACONST_NULL, 
/* 0x03b9: */ _ARETURN, 

/* method@0x03ba: protected javacard/security/RandomData/<init>()V */
0x01, 0x10, 
/* 0x03bc: */ _ALOAD_0, 
/* 0x03bd: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x03c0: */ _RETURN, 

/* method@0x03c1: public abstract javacard/security/RandomData/generateData([BSS)V */
0x40, 0x40, 

/* method@0x03c3: public abstract javacard/security/RandomData/setSeed([BSS)V */
0x40, 0x40, 

/* class@0x03c5: public javacard/security/KeyBuilder */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* method@0x03cf:  javacard/security/KeyBuilder/<init>()V */
0x01, 0x10, 
/* 0x03d1: */ _ALOAD_0, 
/* 0x03d2: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x03d5: */ _RETURN, 

/* method@0x03d6: public static javacard/security/KeyBuilder/buildKey(BSZ)Ljavacard/security/Key; */
0x01, 0x30, 
/* 0x03d8: */ _ACONST_NULL, 
/* 0x03d9: */ _ARETURN, 

/* class@0x03da: public abstract javacard/security/Signature */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x07, 0x00, 0x00, 
HIGH(0x0401), LOW(0x0401),		/* javacard/security/Signature/getAlgorithm()B */
HIGH(0x0403), LOW(0x0403),		/* javacard/security/Signature/getLength()S */
HIGH(0x03fd), LOW(0x03fd),		/* javacard/security/Signature/init(Ljavacard/security/Key;B)V */
HIGH(0x03ff), LOW(0x03ff),		/* javacard/security/Signature/init(Ljavacard/security/Key;B[BSS)V */
HIGH(0x0407), LOW(0x0407),		/* javacard/security/Signature/sign([BSS[BS)S */
HIGH(0x0405), LOW(0x0405),		/* javacard/security/Signature/update([BSS)V */
HIGH(0x0409), LOW(0x0409),		/* javacard/security/Signature/verify([BSS[BSS)Z */

/* method@0x03f2: public static final javacard/security/Signature/getInstance(BZ)Ljavacard/security/Signature; */
0x01, 0x20, 
/* 0x03f4: */ _ACONST_NULL, 
/* 0x03f5: */ _ARETURN, 

/* method@0x03f6: protected javacard/security/Signature/<init>()V */
0x01, 0x10, 
/* 0x03f8: */ _ALOAD_0, 
/* 0x03f9: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x03fc: */ _RETURN, 

/* method@0x03fd: public abstract javacard/security/Signature/init(Ljavacard/security/Key;B)V */
0x40, 0x30, 

/* method@0x03ff: public abstract javacard/security/Signature/init(Ljavacard/security/Key;B[BSS)V */
0x40, 0x60, 

/* method@0x0401: public abstract javacard/security/Signature/getAlgorithm()B */
0x40, 0x10, 

/* method@0x0403: public abstract javacard/security/Signature/getLength()S */
0x40, 0x10, 

/* method@0x0405: public abstract javacard/security/Signature/update([BSS)V */
0x40, 0x40, 

/* method@0x0407: public abstract javacard/security/Signature/sign([BSS[BS)S */
0x40, 0x60, 

/* method@0x0409: public abstract javacard/security/Signature/verify([BSS[BSS)Z */
0x40, 0x70, 

/* class@0x040b: public abstract interface javacardx/crypto/KeyEncryption */
0x80, 
/* class@0x040c: public abstract javacardx/crypto/Cipher */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x05, 0x00, 0x00, 
HIGH(0x0431), LOW(0x0431),		/* javacardx/crypto/Cipher/doFinal([BSS[BS)S */
HIGH(0x042f), LOW(0x042f),		/* javacardx/crypto/Cipher/getAlgorithm()B */
HIGH(0x042b), LOW(0x042b),		/* javacardx/crypto/Cipher/init(Ljavacard/security/Key;B)V */
HIGH(0x042d), LOW(0x042d),		/* javacardx/crypto/Cipher/init(Ljavacard/security/Key;B[BSS)V */
HIGH(0x0433), LOW(0x0433),		/* javacardx/crypto/Cipher/update([BSS[BS)S */

/* method@0x0420: public static final javacardx/crypto/Cipher/getInstance(BZ)Ljavacardx/crypto/Cipher; */
0x01, 0x20, 
/* 0x0422: */ _ACONST_NULL, 
/* 0x0423: */ _ARETURN, 

/* method@0x0424: protected javacardx/crypto/Cipher/<init>()V */
0x01, 0x10, 
/* 0x0426: */ _ALOAD_0, 
/* 0x0427: */ _INVOKESPECIAL, HIGH(0x000c), LOW(0x000c), 
/* 0x042a: */ _RETURN, 

/* method@0x042b: public abstract javacardx/crypto/Cipher/init(Ljavacard/security/Key;B)V */
0x40, 0x30, 

/* method@0x042d: public abstract javacardx/crypto/Cipher/init(Ljavacard/security/Key;B[BSS)V */
0x40, 0x60, 

/* method@0x042f: public abstract javacardx/crypto/Cipher/getAlgorithm()B */
0x40, 0x10, 

/* method@0x0431: public abstract javacardx/crypto/Cipher/doFinal([BSS[BS)S */
0x40, 0x60, 

/* method@0x0433: public abstract javacardx/crypto/Cipher/update([BSS[BS)S */
0x40, 0x60, 

/* class@0x0435: final [B */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* class@0x043f: final [S */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* class@0x0449: final [Z */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* class@0x0453: final [L; */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* class@0x045d: final [I */
0x00, HIGH(0x0000), LOW(0x0000), 0x00, 0xff, 0x00, 0x01, 0x00, 0x00, 0x00, 

/* Export components of masked packages */
/* java/lang */
0x0a, 0x00, 0x49, 0x0c, 0x00, 0x00, 0x00, 0x01, 
0x00, 0x0c, 0x00, 0x13, 0x00, 0x01, 0x00, 0x1d, 
0x00, 0x24, 0x00, 0x01, 0x00, 0x2e, 0x00, 0x35, 
0x00, 0x01, 0x00, 0x3f, 0x00, 0x46, 0x00, 0x01, 
0x00, 0x50, 0x00, 0x57, 0x00, 0x01, 0x00, 0x61, 
0x00, 0x68, 0x00, 0x01, 0x00, 0x72, 0x00, 0x79, 
0x00, 0x01, 0x00, 0x83, 0x00, 0x8a, 0x00, 0x01, 
0x00, 0x94, 0x00, 0x9b, 0x00, 0x01, 0x00, 0xa5, 
0x00, 0xac, 0x00, 0x01, 0x00, 0xb6, 0x00, 0xbd, 
0x00, 0x01, 0x00, 0xc7, 
/* javacard/framework */
0x0a, 0x00, 0xa5, 0x11, 0x00, 0xce, 0x00, 0x00, 
0x00, 0xcf, 0x00, 0x00, 0x00, 0xd0, 0x00, 0x00, 
0x00, 0xd1, 0x00, 0x02, 0x00, 0xf3, 0x00, 0xfa, 
0x01, 0x0a, 0x00, 0x02, 0x01, 0x18, 0x01, 0x26, 
0x01, 0x29, 0x00, 0x02, 0x01, 0x37, 0x01, 0x45, 
0x01, 0x48, 0x00, 0x01, 0x01, 0x5c, 0x01, 0x77, 
0x00, 0x02, 0x01, 0x81, 0x01, 0x89, 0x01, 0x8c, 
0x00, 0x10, 0x01, 0xc0, 0x01, 0xbd, 0x01, 0xc3, 
0x01, 0xb5, 0x01, 0xd6, 0x01, 0xce, 0x01, 0xd2, 
0x01, 0xc6, 0x01, 0xca, 0x01, 0xb1, 0x01, 0x9d, 
0x01, 0xb9, 0x01, 0xa1, 0x01, 0xa5, 0x01, 0xad, 
0x01, 0xa9, 0x01, 0xda, 0x00, 0x01, 0x01, 0xfb, 
0x02, 0x1e, 0x00, 0x04, 0x02, 0x47, 0x02, 0x4b, 
0x02, 0x4f, 0x02, 0x73, 0x02, 0x76, 0x00, 0x02, 
0x02, 0x80, 0x02, 0x88, 0x02, 0x8b, 0x00, 0x02, 
0x02, 0x95, 0x02, 0x9d, 0x02, 0xa0, 0x00, 0x02, 
0x02, 0xaa, 0x02, 0xb2, 0x02, 0xb5, 0x00, 0x02, 
0x02, 0xbf, 0x02, 0xc7, 0x02, 0xca, 0x00, 0x03, 
0x02, 0xd4, 0x02, 0xdc, 0x02, 0xe4, 0x02, 0xe7, 
0x00, 0x07, 0x02, 0xfd, 0x02, 0xf1, 0x02, 0xf5, 
0x02, 0xf9, 0x03, 0x05, 0x03, 0x01, 0x03, 0x09, 

/* javacard/security */
0x0a, 0x00, 0x5b, 0x11, 0x03, 0x14, 0x00, 0x00, 
0x03, 0x15, 0x00, 0x00, 0x03, 0x16, 0x00, 0x00, 
0x03, 0x19, 0x00, 0x00, 0x03, 0x1c, 0x00, 0x00, 
0x03, 0x1f, 0x00, 0x00, 0x03, 0x26, 0x00, 0x00, 
0x03, 0x2d, 0x00, 0x00, 0x03, 0x32, 0x00, 0x00, 
0x03, 0x37, 0x00, 0x00, 0x03, 0x3c, 0x00, 0x00, 
0x03, 0x6a, 0x00, 0x02, 0x03, 0x7e, 0x03, 0x82, 
0x03, 0x93, 0x00, 0x02, 0x03, 0x9d, 0x03, 0xa5, 
0x03, 0xc5, 0x00, 0x01, 0x03, 0xd6, 0x03, 0xa8, 
0x00, 0x02, 0x03, 0xb6, 0x03, 0xba, 0x03, 0xda, 
0x00, 0x02, 0x03, 0xf2, 0x03, 0xf6, 0x03, 0x41, 
0x00, 0x02, 0x03, 0x54, 0x03, 0x5b, 
/* javacardx/crypto */
0x0a, 0x00, 0x0d, 0x02, 0x04, 0x0b, 0x00, 0x00, 
0x04, 0x0c, 0x00, 0x02, 0x04, 0x20, 0x04, 0x24, 

/* VM Array Implementation */
0x0a, 0x00, 0x01, 0x00, 

/* Initial exception table */
0, 
/* Initial exception table list */
HIGH(0x0000), LOW(0x0000), HIGH(0x05cd), LOW(0x05cd), 

};
ROM_ARRAY(u8, staticinit) = {
 NULL 
};
ROM_ARRAY(struct applet, applets) = {
 NULL 
};

#if POST_ISSUANCE_INSTALL
ROM_ARRAY(struct package, packages) = {
/* java/lang */
{ { 7, { 0xa0, 0x00, 0x00, 0x00, 0x62, 0x00, 0x01, } }, 1, 0, 0 },

/* javacard/framework */
{ { 7, { 0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x01, } }, 1, 2, 76 },

/* javacard/security */
{ { 7, { 0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x02, } }, 1, 2, 244 },

/* javacardx/crypto */
{ { 7, { 0xa0, 0x00, 0x00, 0x00, 0x62, 0x02, 0x01, } }, 1, 2, 338 },

/* VM Array Implementation */
{ { 9, { 0xa0, 0x00, 0x00, 0x00, 0x62, 0x03, 0x01, 0x01, 0x01, } }, 1, 0, 354 },

};

#endif /* __POST_ISSUANCE_INSTALL__ */
#endif /* __MASK_HEADER__ */

